### ISSUE TITLE
checking vulnerabilities in code 

### ISSUE THREAD

**Issue by kitarp29** [kitarp29/kube-ez#20]
[Use this](https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck#section-documentation) to find the vulnerabilities of my code. We might have to find an automated process to integrate it into github actions so that each push is tested for vulnerability

**Comment by riju951** [comment]
Please assign this issue to me

**Comment by kitarp29** [comment]
Assigned @riju951 !
Let me know about the pathway you want to take on this one over this weekend.

**Comment by riju951** [comment]
Can I get some more time ?

**Comment by kitarp29** [comment]
Sure, Man!
Just try to complete the work during the timeline of SLoP.
I will help you even after that, but that might not help you in getting SLoP

**Comment by kitarp29** [comment]
Any updates @riju951 ??
Need some help?

**Comment by kitarp29** [comment]
Hey @riju951 you still wanna work on it??
Or should unassign it?

**Comment by riju951** [comment]
I'm so sorry
But I couldn't manage my time
You can unassign
Sorry for Inconvenience

**Comment by kitarp29** [comment]
No inconvenience at all Bro, I understand. Life happens😊
If you are interested you can still work on it!

**Comment by kitarp29** [comment]
I have enabled CodeScanning on this Repo provided by Github.
Read more on this [Here](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql)
Thus closing this issue.
