### ISSUE TITLE
Reduce the size of the Docker Image

### ISSUE THREAD

**Issue by kitarp29** [kitarp29/kube-ez#27]
Right now the Image is like 500 MB or something I am not happy with it
I want to reduce to at least half.

**Comment by kitarp29** [comment]
Problem: I wanted to reduce my docker image for this : https://hub.docker.com/repository/docker/kitarp29/k8s-api
Tag:5.0 is around 500 MB and uses Golang image

I wanted to reduce it to half 

Solution tried:
I tried using an Alpine image of Golang.
As it happens that Go' alpine doesn't have **gcc** installed. I added a **RUN** command in my Dockerfile.
Current DockerFile:
```
FROM golang:alpine3.17
WORKDIR /k8s-api
COPY . .
RUN apk add build-base gcompat && go mod tidy
CMD ["go","run","server.go"]
EXPOSE 8000
```

Blocker: 
**gcc** is still not being installed in the container as it runs. When I run the container and try to access my Go Project the error I get is this:
```
❯ kubectl logs kube-ez -f
# command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exec: "gcc": executable file not found in $PATH
```

If I exec in the container and install **gcc**, then this works but **RUN** command doesn't;t seem to be dong it's job properly!

**Comment by kitarp29** [comment]
We reduced the Docker Image to around 30% with this Merge 🥳

**Comment by kitarp29** [comment]
We will try to reduce it further!

![no-way-home-spider-man-no-way-home](https://user-images.githubusercontent.com/56778773/210205584-6b4c64ac-9a84-4137-9456-ce9d7bbc7b40.gif)

**Comment by kitarp29** [comment]
With the 7th version: [Here](https://hub.docker.com/layers/kitarp29/k8s-api/7.0/images/sha256-abbf15d5c170afec76abe8904b290253329c9de64a206fd8a851c276e2422cde?context=repo)

I applied a multistage build pattern. Made a binary on the build stage and used it to run the container.
Now the image size was: ~35 MB

**Comment by kitarp29** [comment]
Decreased the Docker Image size to **16MB** from **~500MB** !!
This is a decrease of about **97%** 🥳 
Yes, even I can't believe it.

Further reduced the size of the Golang Binary by removing the dependency of ```gcc```
It was a trade-off between the speed of creating the container and the memory of the Docker Image. 

But did it Finally!!

![cheers-leonardo-dicaprio](https://user-images.githubusercontent.com/56778773/210216090-3fc85675-7fda-4bdb-b92b-5cfe77249d1c.gif)

**Comment by Osiephri** [comment]
Great work kitarp

**Comment by kitarp29** [comment]
If someone reads to read more on this issue, refer this:
https://dev.to/kitarp29/reducing-docker-image-size-a67
